from tkinter import *
import tkinter as tk
import numpy as np
from PIL import Image, ImageTk
from tkinter import filedialog
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.mobilenet_v2 import preprocess_input
from keras.applications.mobilenet_v2 import decode_predictions
from keras.applications.mobilenet_v2 import MobileNetV2
root = tk.Tk()


model = MobileNetV2()



def switch_index(index):
    switcher = {
        0: "Tench, Tinca tinca\nThey effectively prevent blooms of algae in water and reduce eutrophication.",
        1: "Goldfish, Carassius auratus\nThey control the populations of insects such as mosquito larvae, small crustaceans, zooplankton, and detritus.",
        2: "Great White Shark, Carcharodon carcharias\nThey are apex predators meaning they have a large affect on the populations of their prey.\nThey are hosts to parasites such as copepods.",
        3: "Tiger Shark, Galeocerdo cuvieri\nAs top predators in their ecosystem they control populations of prey species.\n Tiger sharks also serve as a host for remoras, which are small suckerfish.",
        4: "Hammerhead, Sphyrna mokarran\nThey are among the largest of reef sharks, making them\ntop predators of the animals on which they prey.\nThey are also host to several types of ectoparasitic invertebrates.",
        5: "Electric Ray, Crampfish, Numbfish, Torpedo, Torpediniformes\nTPhe common torpedo can subdue prey and deter threats with strong electric shocks.\nThey feed on a wide variety of benthic and benthopelagic fish.",
        6: 'Stingray, Dasyatidae\nThey are a consistent predator on populations of mollusks, crustaceans, worms, and fishes.\nThey, in turn, provide food for sharks and other large fishes. ',
        107: 'Jellyfish, Scyphozoa\nThey keep a check on plankton and small organisms in aquatic ecosystems.',
        108: 'Sea anemone, Actiniaria\nIt controls the popuations of mainly copepods and midge larvae in salt marshes.',
        112: 'Conch, Aspidogaster conchicola\n It plays an important role in regulating the abundance of seagrass detritus.',
        115: 'Sea slug, Ndibranch\nBy munching on the decomposing plant matter on the ocean floor, the sea slug is\nof great benefit to every marine environment the sea slug inhabits.',
        116: 'Chiton, coat-of-mail shell, sea cradle, polyplacophore\nChitons are important for their role as primary consumers of marine plants.',
        117: 'Chambered nautilus, pearly nautilus, Nautilus pompilius\nThey keep algae population in check.',
        118: 'Dungeness crab, Cancer magister\nCancer magister eat a variety of marine invertebrates and fish to keep marine ecosystems stable.',
        119: 'Rock crab, Cancer irroratus\nThey help to clean up the sea bottom by harvesting decomposing plant and animal matter.',
        120: 'Fiddler crab\nThey maintain the population of cordgrass.\nThey help to stimulate the turnover of nutrients in the soil.',
        121: 'King crab, Alaska crab, Paralithodes camtschatica\nThey help to clean up the sea bottom by harvesting decomposing plant and animal matter.',
        122: 'American lobster, Maine lobster, Homarus americanus\nLobsters function in the transfer of energy and materials from primary producers\n and primary consumers to apex predators.',
        123: 'Spiny lobster, langouste, rock lobster, crayfish, sea crawfish\nMany organisms live on the exoskeleton and other organisms are internally parasitic in crayfish.',
        124: 'Crayfish, crawfish, Cambarus sp.\nMany organisms live on the exoskeleton and other organisms are internally parasitic in crayfish.',
        125: 'Hermit crab, Paguroidea\nThey help to clean up the sea bottom by harvesting decomposing plant and animal matter.',
        126: 'Isopod, Isopoda\nIsopods play an important role in ecosystems by aiding in the decomposition of plant material\nand by enhancing the activity of microbes.',
        147: 'Grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus\nGray whales are hosts to parasites, including barnacles and whale lice.\nThey are major predators of benthic amphipods (Amphipoda) and other marine invertebrates',
        148: 'Killer whale, killer, orca, grampus, sea wolf, Orcinus orca\nThey are top predators in marine ecosystems and impact the populations of common prey.\nKiller whales are host to some endoparasites and ectoparasites.',
        149: 'Dugong, Dugong dugon\nTheir grazing contributes to nutrient cycling and energy flow as they stir up sediment.\nTheir fecal matter also acts as a fertilizer, which helps seagrass to quickly reestablish.',
        150: 'Sea lion, Otariinae\nThis species is probably a component of control on fish and penguin populations.',
        327: 'Starfish, sea star, Asteroidea\nThey are probably the most important predator of the shallow ecosystem\nTheir feeding activities control the whole ecosystem',
        328: 'Sea urchin, Echinoidea\nThey play a critical role in maintaining the balance between corals and algae.',
        329: 'Sea cucumber, Holothurian\nThey help recycle nutrients, breaking down detritus and other organic matter\nafter which bacteria can continue the degradation process.',
        389: 'Barracouta fish, Snoek\nAn endangered species that is a top predator in marine world.',
        390: 'Eel, Anguilla rostrata\nEels are both a food source and a predator of organisms in their ecosystem.',
        391: 'Coho, blue jack, silver salmon, Oncorhynchus kisutch\nThey are both a food source and a predator of organisms in their ecosystem.',
        392: 'Rock beauty, Holocanthus tricolor\nThey are both a food source and a predator of organisms in their ecosystem.',
        393: 'Anemone fish, Amphiprioninae\nThey are both a food source and a predator of organisms in their ecosystem.',
        394: 'Sturgeon, Acipenseridae\nThey are both a food source and a predator of organisms in their ecosystem.',
        395: 'Gar, garfish, garpike, billfish, Lepisosteus osseus\nThey are both a food source and a predator of organisms in their ecosystem.',
        396: 'Lionfish\nThey are both a food source and a predator of organisms in their ecosystem.',
        397: 'Puffer, pufferfish, blowfish, globefish, Tetraodontidae\nThey are both a food source and a predator of organisms in their ecosystem.',
        7: 'Cock, Gallus gallus\nThese birds are important food source for humans.\nThey take in weeds and bugs from the paddock and give the farmer financial\nand ecological liberation from synthetic pesticides and herbicides.',
        8: 'Hen, Gallus gallus domesticus\nGallus gallus\nThese birds are important food source for humans.\nThey take in weeds and bugs from the paddock and give the farmer financial\nand ecological liberation from synthetic pesticides and herbicides.',
        9: 'Ostrich, Struthio camelus\nThey are very selective feeders, taking the seed heads of grasses and certain flowers and seeds.\nSo they are effective seed dispersers.',
        10: 'Brambling, Fringilla montifringilla\nThey scan large areas for suitable beech mast crops.\nThey presumably play an important role as seed predators at foraging sites.',
        11: 'Goldfinch, Carduelis carduelis\nGoldfinch participates in is the dispersion of seeds.\nAlso, they provide a source of food for birds of prey, snakes, and other predators.',
        12: 'House finch, linnet, Carpodacus mexicanus\nHouse finches are important seed predators and dispersers.\nAlso, they provide a source of food for birds of prey, snakes, and other predators.',
        13: 'Junco, snowbird, Junco hyemalis\nThey aid in the dispersal of seeds and help to control insect populations. ',
        14: 'Indigo bunting, indigo finch, indigo bird, Passerina cyanea\nThey consume many varieties and amounts of food\nThey serve as food for others and hosts for parasites(hippoboscid flies)\nThey help distribute seeds of the plants whose berries they eat.',
        15: 'Robin, American robin, Turdus migratorius\nThey are important as prey items to their predators\n They control some insect populations\nThey disperse the seeds of the fruits they eat.',
        16: 'Bulbul, Pycnonotidae\nThey aid in the dispersal of seeds and help to control insect populations.',
        17: 'Jay, Cyanocitta\nThey aid in the dispersal of seeds and help to control insect populations.',
        18: 'Magpie, Pica pica\nmagpies have a symbiotic relationship with large ungulates such as deer\nThe sturdy nests built by black-billed magpies last long and are often reused by other birds.',
        19: 'Chickadee Parus carolinensis\nThey are a prey for small avian, mammalian, and snake predators.\nThey are important predators on seeds and small insects and insect larvae',
        20: 'Water ouzel, Dipper, Cinclus mexicanus\nThey control the population of small aquatic plants and freshwater invertebrates.',
        21: 'Kite, Milvus migrans\nBlack kites play an essential role as efficient scavengers within their ecosystems.\nA variety of external parasites are found on black kites, as well as endoparasitic trematodes.',
        22: 'Bald eagle, Haliaeetus leucocephalus\nAs a top predator, bald eagles impact all members of their trophic community.\nTheir decline and recent population resurgence has impacted many other organisms',
        23: 'Vulture, Aegypius Monachus\nTheir presence is essential for other species as they usually eat the flesh before other smaller scavengers.\nTheir population is declining and their complete disappearance could have disastrous results. ',
        24: 'Great grey owl, Strix nebulosa\nThey scavenge and dispose of carrion and provide a check on rodent populations.',
        80: 'Black grouse, Canachites canadensis\nThey help maintain sustainable population levels of their prey and predator species\nand, after death, provide food for scavengers and decomposers.',
        81: 'Ptarmigan, Lagopus muta\nThey help maintain sustainable population levels of their prey and predator species\nand, after death, provide food for scavengers and decomposers.',
        82: 'Ruffed grouse, partridge, Bonasa umbellus\nThey help maintain sustainable population levels of their prey and predator species\nand, after death, provide food for scavengers and decomposers.',
        83: 'Prairie chicken, prairie grouse, prairie fowl, Tympanuchus pallidicinctus\nThey help maintain sustainable population levels of their prey and predator species\nand, after death, provide food for scavengers and decomposers.',
        84: 'Peacock, Indian blue peafowl, Pavo cristatus \nThey help maintain sustainable population levels of their prey and predator species\nand, after death, provide food for scavengers and decomposers.',
        85: 'Quail, Perdicula asiatica\nJungle bush-quail have an impact on the plant seeds and prey they consume.',
        86: 'Partridge, Dendrortyx barbatus\nFeeding on fruits, nuts, and seeds, they aid plants in reproduction by dispersing some plant seeds.',
        87: 'African grey parrot, Psittacus erithacusAfrican grey parrots may disperse the seeds of fruits they eat.\nThey act as definitive hosts to both tapeworms and blood parasites.',
        88: 'Macaw\nThey consume the fruit of cactus trees and the seeds of faveleira and pinhao trees\nand could be effective seed dispersers. ',
        89: 'Sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita\nThey are effective seed dispersers.',
        90: 'Lorikeet, Loriini, Trichoglossus moluccanus\nThey are effective seed dispersers.\nAfter death, they provide food for scavengers and decomposers.',
        91: 'Coucal, Centropus\nThey help maintain sustainable population levels of their prey and predator species\nand, after death, provide food for scavengers and decomposers.',
        92: 'Bee eater, Merops apiaster\nBurrowing breeding behavior helps rain, sunlight, and nutrients to penetrate soil.\nAbandoned burrows provide shelter for other species to colonize the area\nBurrows provide access to invertebrate prey items which increase food web complexity.',
        93: 'Hornbill, Bucorvus\nThey help maintain sustainable population levels of their prey and predator species\nand, after death, provide food for scavengers and decomposers.',
        94: 'Hummingbird, Trochilidae\nThey are effective seed dispersers.',
        95: 'Jacamar, Galbulidae\nThey help maintain sustainable population levels of their prey and predator species\nand, after death, provide food for scavengers and decomposers.',
        96: 'Toucan, Ramphastidae\nThey help maintain sustainable population levels of their prey and predator species\nand, after death, provide food for scavengers and decomposers.',
        97: 'Drake duck, Anas platyrhynchos Linnaeus\nThey are important predators of small fish and insects in their wetland habitats',
        98: 'Red-breasted merganser, Mergus serrator\nThey are important predators of small fish in their wetland habitats',
        99: 'Goose, Anseranas semipalmata\nThey are effective seed dispersers.',
        100: 'Black swan, Cygnus atratus\nThey help maintain sustainable population levels of their prey and predator species\nand, after death, provide food for scavengers and decomposers.',
        127: 'Wite stork, Ciconia ciconia\nWhite storks influence the populations of their prey items.\nWhite Stork nests are also important as seed banks for seed plants',
        128: 'Back stork, Ciconia nigra\nBlack storks influence the populations of their prey items.\nTheir nests are also important as seed banks for seed plants',
        129: 'Spoonbill, Ajaia ajaja\nSpoonbill controls minnow, small crustacean, bits of plant and insect numbers in water systems.',
        130: 'Flamingo, Phoenicopterus roseus\nFlamingos impact populations of aquatic algae, diatoms, and plankton.',
        131: 'Little blue heron, Egretta caerulea\nThe Little Blue Heron is enjoyable to watch and helps control insect populations.',
        132: 'American egret, great white heron, Egretta albus\nIt helps control insect populations.',
        133: 'Bittern, Botaurus\nIt helps control insect, amphibian, crayfish, and small fish and some mammal population.',
        134: 'Crane, Gruidae\nSeeds make up a portion of grey-crowned cranes diets, thus the birds\nare likely an important seed disperser for the plants.',
        135: 'Limpkin, Aramus pictus\nThey control minnow, small crustacean, bits of plant and insect numbers in water systems.',
        136: 'European gallinule, Porphyrio porphyrio\nThey are important predators of marsh invertebrates and impact marsh communities\nthrough their predation and browsing.',
        137: 'American coot, marsh hen, mud hen, water hen, Fulica americana\nAmerican Coots influence populations of aquatic invertebrates and plants\nand serve as a prey base for predators in their habitats.',
        138: 'Bustard, Otididae\nThey likely help with insect population control as well as seed dispersal for plants.',
        139: 'Ruddy turnstone, Arenaria interpres\nThey are important predators of insects and other invertebrates in their tundra breeding habitats\nand crustaceans and mollusks in coastal habitats',
        140: 'Red-backed sandpiper, dunlin, Erolia alpina\nThey tend to be carriers of blood parasites such as Haemoproteus contortus.\nCommon sandpipers are also carriers of various other common avian parasites.',
        141: 'Redshank, Tringa totanus\nRedshank detects its prey by sight, feeding on various prey by\npecking or probing the mud thus help soil recycle',
        142: 'Dowitcher, Limnodromus semipalmatus\nLong-billed dowitcher uses its long bill to poke in the mud and find food hence aids soil recycle.',
        143: 'Oystercatcher Haematopus palliatus\nThey are an indicator species whose presence in certain areas\ncan help humans infer the environmental conditions of those sites.',
        144: 'Pelican, Pelecanus\nThey control fish populations.',
        145: 'King penguin, Aptenodytes patagonica\nThey serve as food for predators such as leopard seals and seabirds in cold areas,\nalong with foxes, leopards, and even crabs in warmer climates.',
        146: 'Albatross, mollymawk\nThey are the waste managers of the ocean.\nThey will eat any edible floating debirs, including garbage and animal matter.',
        25: 'European fire salamander, Salamandra salamandra\nThey keep a check on small insect population\nA popular species in the pet trade, and has also been utilized as an animal model in research.',
        26: 'Common newt, Triturus vulgaris\nIt is mainly an insect eater, important in keeping insect populations in check',
        27: 'Eft,  juvenile Newt\nIt is mainly an insect eater, important in keeping insect populations in check',
        28: 'Spotted salamander, Ambystoma maculatum\nThey affect the abundance and diversity of other species in the pools, especially other amphibians.',
        29: 'Axolotl, mud puppy, Ambystoma mexicanum\nThey are top predators in their environment, important in structuring community dynamics.',
        30: 'Bullfrog, Rana catesbeiana\nbullfrogs help to control insect pests.\nThey are important for medical research.\nThey have an important place in the food chain as both predators and prey.',
        31: 'Tree frog, Hyla\n They help to control insect pests.\nThey are important for medical research.\nThey have an important place in the food chain as both predators and prey.',
        32: 'Tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui\nThey act as the dominant herbivore in some stream habitats\nAs a juvenile or adult, they may play an active part in both aquatic and terrestrial ecosystems.',
        33: 'Loggerhead turtle, Caretta caretta\nIt feeds on large numbers of invertebrates, affecting their populations\nTheir broken shells are used as a calcium source for other species.',
        34: 'Leatherback turtle, Dermochelys coriacea\nIt eats mainly jellyfish and other soft-bodied marine animals\nLeatherback eggs and hatchlings may be a significant food source for egg predator populations',
        35: 'Mud turtle, Kinosternon flavescens\nFeces from Kinosternon flavescens helps with soil fertilization.\nThey regulate population size of small fishes and amphibians.',
        36: 'Terrapin, Testudines\nThey control populations of snails, other mollusks, crustaceans, fish, insects, and carrion',
        37: 'Box turtle, Terrapene, \nThis species can be useful as seed dispersers, as they distribute them through their feces.\nThey also feed on carrion, contributing to biodegradation.\nThey also serve as prey for dogs, coyotes, and many other animal species.',
        38: 'Banded gecko, Coleonyx\nBanded geckos eat many invertebrates, and are prey to many vertebrates.',
        39: 'Common iguana, Iguana iguana\nThey help disperse seeds, and provide a source of food for larger predatory animals\nIguanas can be indicators of environmental changes\nBy watching their responses, we can be alerted to possible problems before we detect with our own senses.',
        40: 'Chameleon, Anolis carolinensis\nIts greatest impact is as a prey species.\nThey consume seeds and grains, potentially aiding in seed dispersal.',
        41: 'Whiptail Lizard, Cnemidophorus\nLizards are useful in the control of insect pests',
        42: 'Rainbow Lizard, Agama\nLizards are useful in the control of insect pests\nThey also eat small mammals, small reptiles, and vegetation such as flowers, grasses, and fruits.',
        43: 'Frilled lizard, Chlamydosaurus kingi\nThey are insectivores and most commonly eat small invertebrates\nThey have been known to eat small mammals and pieces of meat',
        44: 'Alligator lizard, Elgaria\nLizards are useful in the control of insect pests',
        45: 'Gila monster, Heloderma suspectum\nThey prey on a variety of small mammals, birds, lizards, and eggs ',
        46: 'green lizard, Lacerta viridis\nLizards are useful in the control of insect pests\nThey also eat small mammals, small reptiles, and vegetation such as flowers, grasses, and fruits.',
        47: 'African chameleon, Chamaeleo chamaeleon\nIts greatest impact is as a prey species.\nThey consume seeds and grains, potentially aiding in seed dispersal.',
        48: 'Komodo dragon, dragon lizard, Varanus komodoensis\nLizards are useful in the control of insect pests',
        49: 'African crocodile, Nile crocodile, Crocodylus niloticus\nCrocodiles perform a role in maintaining the structure and function of fresh water ecosystems\nThey are a top predator and keystone species affecting all animals below them in the food chain.',
        50: 'American alligator, Alligator mississipiensis\nThe American alligator is a host for the ectoparasite, the sea turtle barnacle\nThey are illegally hunted for meat, skin, and teeth which is a concern.',
        52: 'Thunder snake, worm snake, Carphophis amoenus\nThey keep the pest population down by feeding on mice\nand other small rodents that damage crops and carry disease.',
        53: 'Ringneck snake, ring-necked snake, Diadophis punctatus\nThey keep the pest population down by feeding on \nmice and other small rodents that damage crops and carry disease.',
        54: 'Hognose snake, puff adder, sand viper, Heterodon nasicus\nThey keep the pest population down by feeding on\nmice and other small rodents that damage crops and carry disease.\nThey are hosts to several parasites',
        55: 'Green snake, grass snake, Opheodrys\nThey keep the pest population down and prey on small birds.',
        56: 'King snake, Lampropeltis\nThey keep the pest population down by feeding on mice and other small rodents that damage crops and carry disease.',
        57: 'Garter snake, grass snake, Thamnophis\nThey keep the pest population down by feeding on \nmice and other small rodents that damage crops and carry disease.',
        58: 'Water snake\nThey live near or in water to prey on fish and amphibians (frogs, toads and salamanders).',
        59: 'Vine snake\nThey keep the pest and small bird population population down.',
        60: 'Night snake, Hypsiglena torquata\nThey keep the pest population down by feeding on mice and other small rodents that damage crops and carry disease.',
        61: 'Boa constrictor, Constrictor constrictor\nThey keep the pest population and also prey\non birds and small mammals including bats.',
        62: 'Rock python, rock snake, Python sebae\nThey keep the pest population down by feeding on\nmice and other small rodents that damage crops and carry disease.',
        63: 'Indian cobra, Naja naja\nThey keep the pest population down by feeding on\nmice and other small rodents that damage crops and carry disease.\nThey also feed on other snakes',
        64: 'green mamba\nThey keep the pest population down by feeding on\nmice and other small rodents that damage crops and carry disease.',
        65: 'sea snake\nThey are top predators and may play a role in the population control\nof the species that it eats, such as small fish and eels',
        66: 'Horned viper, cerastes, sand viper, horned asp, Cerastes cornutus\nThey keep the pest population down by feeding on mice and other small rodents that damage crops and carry disease.',
        67: 'Diamondback, diamondback rattlesnake, Crotalus adamanteus\nIt preys on small mammals and birds, and sometimes other reptiles and amphibians, and even fish and invertebrates.',
        68: 'Sidewinder, horned rattlesnake, Crotalus cerastes\nThey keep the pest population down by feeding on mice and other small rodents that damage crops and carry disease.',
        69: 'Trilobite\nAn extinct species that ranks among the most important of early animals.',
        70: 'Harvestman, daddy longlegs, Phalangium opilio\nIt has been noted to feed on pest species like beetle larvae.',
        71: 'Scorpion, Scorpionidae\nThey serve an important role in the food web by helping to control the insect population.',
        72: 'Black and gold garden spider, Argiope aurantia\nThey are important predators of grasshoppers in rangeland ecosystems.\nThey serve an important role in the food web by helping to control the insect population.',
        73: 'Barn spider, Araneus cavaticus\nThey serve an important role in the food web by helping to control the insect population.\nThey are important predators of grasshoppers in rangeland ecosystems',
        74: 'Garden spider, Aranea diademata\nThey serve an important role in the food web by helping to control the insect population.\nThey are important predators of grasshoppers in rangeland ecosystems',
        75: 'Black widow, Latrodectus mactans\nThey serve an important role in the food web by helping to control the insect population.\nThey are important predators of grasshoppers in rangeland ecosystems',
        76: 'Tarantula\nThey serve an important role in the food web by helping to control the insect population.\nThey are important predators of grasshoppers in rangeland ecosystems',
        77: 'Wolf spider, hunting spider\nThey serve an important role in the food web by helping to control the insect population.\nThey are important predators of grasshoppers in rangeland ecosystems',
        78: 'Tick, Dermacentor variabilis\nLarvae and nymphs target smaller mammals such as mice and other rodents,\nwhile adults target larger mammals such as dogs, raccoons, cattle, and humans. ',
        79: 'Centipede, Chilopoda\nThey serve an important role in the food web by helping to control the insect population.',
        113: 'Snail, Achatina fulica\nThis species decomposes and consumes dead vegetation.\nThe snail assists in recycling nutrients and the building blocks essential to life.',
        114: 'Slug, Ariolimax\nThey eat decaying plant material and fungi.\nMost carnivorous slugs on occasion also eat dead specimens of their own kind.',
        300: 'Tiger beetle\nThey prey on other insects, such as many species of leaf beetles that destroy crop plants.',
        301: 'Ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle\nThey prey on other insects, such as many species of leaf beetles that destroy crop plants.',
        302: 'Ground beetle, carabid beetle\nThey prey on other insects, such as many species of leaf beetles that destroy crop plants.',
        303: 'Long-horned beetle, longicorn, longicorn beetle\nThey prey on other insects, such as many species of leaf beetles that destroy crop plants.',
        304: 'Leaf beetle, chrysomelid\nThey prey on other insects, such as many species of leaf beetles that destroy crop plants.',
        305: 'Dung beetle\nThe majority are coprophagous, using the faecal material of various animals for food',
        306: 'Rhinoceros beetle\nThey eat dead and decaying plant matter.',
        307: 'Weevil\nUnfortunately it is a pest but provides food to its predators',
        308: 'Fly\nThe primary ecosystem role of flies is decomposition and recycling of organic material. ',
        309: 'Bee\nBees are important pollinators in natural and agricultural ecosystems.',
        310: 'Ant, emmet, pismire\nAnts turn and aerate the soil, allowing water and oxygen to reach plant roots\nAnts eat a wide variety of organic material and provide food for different organisms.',
        311: 'Grasshopper, hopper\nIt serves as prey to birds, rodents, spiders, and other insects.',
        312: 'Cricket\nThey are important agents in the decomposer communities of many ecosystems. ',
        313: 'Walking stick, walkingstick, stick insect\n.Stick insects eat leaves up in the dense rainforest canopy,\nmaking openings that let sunlight reach the ground.',
        314: 'Cockroach, roach\nThey recycle a large amount of decaying plant and animal matter.',
        315: 'Mantis, mantid\nThis species consumes many insects, including a large number that are agricultural pests.',
        316: 'Cicada, cicala\nCicadas provide trees a service by pruning the weak branches of a tree.',
        317: 'Leafhopper\nLeafhoppers are one of the important groups of insect pests on agricultural crops.',
        318: 'Lacewing, lacewing fly\nLacewings helps to control arthropod pests for several crops, worldwide',
        319: "Dragonfly, Ophiogomphus\nIt provides soil aeration.\nIt is a food source for a wide number of species in the food web",
        320: 'Damselfly, Calopteryx dimidiata\nBoth adults and larvae of Calopteryx dimidiata are predators of insects.\nThey also serve as prey to many other organisms, including birds and fish',
        321: 'Admiral butterfly, Vanessa atalantaare\nThey are important pollinators to most agricultural crops.\nThey are also a food source to predators like birds, spiders, lizards and other animals.',
        322: 'Ringlet, ringlet butterfly\nThey are important pollinators to most agricultural crops.\nThey are also a food source to predators like birds, spiders, lizards and other animals.',
        323: 'Monarch, monarch butterfly, milkweed butterfly, Danaus plexippus\nThey are important pollinators to most agricultural crops.\nThey are also a food source to predators like birds, spiders, lizards and other animals.',
        324: 'Cabbage butterfly\nThey are important pollinators to most agricultural crops.\nThey are also a food source to predators like birds, spiders, lizards and other animals.',
        325: 'Sulphur butterfly, sulfur butterfly\nThey are important pollinators to most agricultural crops.\nThey are also a food source to predators like birds, spiders, lizards and other animals.',
        326: 'Lycaenid, lycaenid butterfly\nThey are important pollinators to most agricultural crops.\nThey are also a food source to predators like birds, spiders, lizards and other animals.',
        101: 'Tusker elephant\nThey eat a very large amount of food daily, which facilitates nutrient cycling.\nBecause of their large size, they transform the habitat by tearing down trees.\nThis creates gaps in the forest, allowing small animals to move around.\nThey also aid in seed dispersal.',
        102: 'Echidna, spiny anteater, Tachyglossidae\nThey play a crucial role in the environment as their digging can make for better soils,\nand in turn influence plant growth and species diversity.',
        103: 'Platypus, duckbill, Ornithorhynchus anatinus\nBy foraging on aquatic invertebrates, they play an integral role in the food webs of\nthe streams, rivers, and billabongs',
        104: 'Wallaby, brush kangaroo, Wallabia\nThis species is an herbivore that may impact its communities by grazing and browsing.',
        105: 'Koala beer, Phascolarctos cinereus\nThey only eat 5 types of euclyptus species hence control their population.\nKoala droppings act as nutrients for the regeneration of undergrowth,\nensuring that the forests regenerate to sustain future life.',
        106: 'Wombat, Vombatidae\nWombats, which dig holes to live in, are credited with breaking up hard soil and recycling\norganic material, such as fallen leaves, through the earth',
        151: 'Chihuahua dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        152: 'Japanese spaniel dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        153: 'Maltese dog, Maltese terrier, Maltese\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        154: 'Pekinese dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        155: 'Shih-Tzu dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        156: 'Blenheim spaniel dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        157: 'Papillon dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        158: 'Toy terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        159: 'Rhodesian ridgeback dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        160: 'Afghan hound\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        161: 'Basset dog, basset hound\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        162: 'Beagle dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        163: 'Bloodhound, sleuthhound\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        164: 'Bluetick dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        165: 'Black-and-tan coonhound dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        166: 'Walker hound, Walker foxhound dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        167: 'English foxhound dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        168: 'Redbone dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        169: 'Rorzoi dog, Russian wolfhound\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        170: 'Irish wolfhound dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        171: 'Italian greyhound dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        172: 'Whippet dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        173: 'Ibizan hound dog, Ibizan Podenco\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        174: 'Norwegian elkhound dog, elkhound\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        175: 'otterhound dog, otter hound\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        176: 'Saluki, gazelle hound\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        177: 'Scottish deerhound, deerhound\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        178: 'Weimaraner\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        179: 'Staffordshire bullterrier dog, Staffordshire bull terrier\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        180: 'American Staffordshire terrier dog, Staffordshire terrier, American pit bull terrier, pit bull terrier\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        181: 'Bedlington terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        182: 'Border terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        183: 'Kerry blue terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        184: 'Irish terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        185: 'Norfolk terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        186: 'Norwich terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        187: 'Yorkshire terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        188: 'Wire-haired fox terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        189: 'Lakeland terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        190: 'Sealyham terrier, Sealyham dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        191: 'Airedale, Airedale terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        192: 'Cairn, cairn terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        193: 'Australian terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        194: 'Dandie Dinmont, Dandie Dinmont terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        195: 'Boston bull, Boston terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        196: 'Miniature schnauzer dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        197: 'Giant schnauzerv dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        198: 'Standard schnauzer dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        199: 'Scotch terrier dog, Scottish terrier, Scottie\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        200: 'Tibetan terrier dog, chrysanthemum dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        201: 'Silky terrier dog, Sydney silky\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        202: 'Soft-coated wheaten terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        203: 'West Highland white terrier dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        204: 'Lhasa dog, Lhasa apso\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        205: 'Flat-coated retriever dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        206: 'Curly-coated retriever dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        207: 'Golden retriever dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        208: 'Labrador retriever dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        209: 'Chesapeake Bay retriever dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        210: 'German short-haired pointer dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        211: 'Vizsla dog, Hungarian pointer\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        212: 'English setter dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        213: 'Irish setter dog, red setter\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        214: 'Gordon setter dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        215: 'Brittany spaniel dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        216: 'Clumber dog, clumber spaniel\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        217: 'English springer dog, English springer spaniel\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        218: 'Welsh springer spaniel dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        219: 'Cocker spaniel, English cocker spaniel, cocker dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        220: 'Sussex spaniel dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        221: 'Irish water spaniel dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        222: 'Kuvasz dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        223: 'Schipperke dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        224: 'Groenendael dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        225: 'malinois dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        226: 'Briard dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        227: 'Kelpie\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        228: 'Komondor\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        229: 'Old English sheepdog, bobtail\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        230: 'Shetland sheepdog, Shetland sheep dog, Shetland\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        231: 'Collie dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        232: 'Border collie dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        233: 'Bouvier des Flandres, Bouviers des Flandres\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        234: 'Rottweiler\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        235: 'German shepherd dog, German police dog, alsatian\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        236: 'Doberman dog, Doberman pinscher\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        237: 'Miniature pinscher\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        238: 'Greater Swiss Mountain dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        239: 'Bernese mountain dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        240: 'Appenzeller dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        241: 'EntleBucher dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        242: 'Boxer dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        243: 'Bull mastiff dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        244: 'Tibetan mastiff dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        245: 'French bulldog dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        246: 'Great Dane\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        247: 'Saint Bernard dog, St Bernard\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        248: 'Eskimo dog, husky\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        249: 'Malamute dog, Alaskan malamute\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        250: 'Siberian husky dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        251: 'Dalmatian, coach dog, carriage dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        252: 'Affenpinscher, monkey pinscher, monkey dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        253: 'Basenji\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        254: 'Pug, pug-dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        255: 'Leonberg\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        256: 'Newfoundland, Newfoundland dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        257: 'Great Pyrenees dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        258: 'Samoyed, Samoyede dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        259: 'Pomeranian\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        260: 'Chow dog, chow chow\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        261: 'Keeshond\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        262: 'Brabancon griffon\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        263: 'Pembroke dog, Pembroke Welsh corgi\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        264: 'Cardigan dog, Cardigan Welsh corgin\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        265: 'Toy poodle dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        266: 'Miniature poodle dogn\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        267: 'Standard poodle dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        268: 'Mexican hairless dog\nBy digging up the soil and exposing it to air, as well as burying bones and food,\n dogs help renew and enrich the environment.',
        269: 'Timber wolf, grey wolf, Canis lupus\nAs top predators, gray wolves are important in regulating populations of their prey animals.',
        270: 'White wolf, Arctic wolf, Canis lupus tundrarum\nAs top predators, they are important in regulating populations of their prey animals.',
        271: 'Red wolf, maned wolf, Canis rufus, Canis niger\nAs top predators, they are important in regulating populations of their prey animals.',
        272: 'Coyote, prairie wolf, brush wolf, Canis latrans\nAs top predators, they are important in regulating populations of their prey animals.',
        273: 'Dingo, warrigal, warragal, Canis dingo\nDingos are the primary mammalian carnivore in Australia.\nThey help to maintain populations of small Australian mammals.\nDingos are also appreciated for their help in controlling European rabbit populations',
        274: 'Dhole, Cuon alpinus\nThe dhole controls populations of wild berries, insects, and lizards.\nPacks of dholes feast on mammals ranging from rodents to deer.',
        275: 'Hyena dog, African hunting dog, Lycaon pictus\nWild dogs may help regulate prey species that in turn play a role in shaping vegetation communities.',
        276: 'Hyena, hyaena\nAs a scavenger, Hyaena brunnea plays an important role in eliminating the remains of old carcasses from its environment.',
        277: 'Red fox\nThey probably help to regulate populations of small mammals through its predatory behavior,\nwhich in turn probably has an effect on the plant communities',
        278: 'Kit fox, Vulpes macrotis\nThey probably help to regulate populations of small mammals through its predatory behavior,\nwhich in turn probably has an effect on the plant communities',
        279: 'Arctic fox, white fox, Alopex lagopus\nThey probably help to regulate populations of small mammals through its predatory\n behavior, which in turn probably has an effect on the plant communities',
        280: 'Grey fox, gray fox, Urocyon cinereoargenteus\nThey probably help to regulate populations of small mammals through its predatory behavior,\nwhich in turn probably has an effect on the plant communities',
        281: 'Tabby, tabby cat\nCats are vital for keeping those pests in check.',
        282: 'Tiger cat\nCats are vital for keeping those pests in check.',
        283: 'Persian cat\nCats are vital for keeping those pests in check.',
        284: 'Siamese cat, Siamese\nCats are vital for keeping those pests in check.',
        285: 'Egyptian cat\nCats are vital for keeping those pests in check.',
        286: 'Cougar, puma, catamount, mountain lion, painter, panther, Felis concolorn\nAs top predators, they are important in regulating populations of their prey animals.',
        287: 'Lynx, catamount\nThey have the ability to influence the population sizes,\ndistribution, and behaviors of some prey species.',
        288: 'leopard, Panthera pardusn\nAs top predators, they are important in regulating populations of their prey animals.',
        289: 'Snow leopard, ounce, Panthera uncia\nAs top predators, they are important in regulating populations of their prey animals.',
        290: 'Jaguar, panther, Panthera onca, Felis onca\nAs top predators, they are important in regulating populations of their prey animals.',
        291: 'Lion, king of beasts, Panthera leo\nAs top predators, they are important in regulating populations of their prey animals.',
        292: 'Tiger, Panthera tigris\nAs top predators, they are important in regulating populations of their prey animals.',
        293: 'Cheetah, chetah, Acinonyx jubatus\nAs top predators, they are important in regulating populations of their prey animals.',
        294: 'Brown bear, bruin, Ursus arctos\nThey are important predators and seed dispersers.',
        295: 'American black bear, black bear, Ursus americanus, Euarctos americanus\nThey are important predators and seed dispersers.',
        296: 'Ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus\nPolar bears are a top carnivore of the arctic.',
        297: 'Sloth bear, Melursus ursinus, Ursus ursinus\nThey are important predators and seed dispersers.',
        298: 'Mongoose\nIt affects plant, vertebrate, and invertebrate populations.',
        299: 'Meerkat, Suricata suricatta\nThey take many invertebrates, controlling on their prey populations.',
        330: 'Wood rabbit, cottontail, cottontail rabbit\nThey convert the energy in plant matter into energy of animal matter\nand thus is an important link in the food web.',
        331: 'Hare\nThey convert the energy in plant matter into energy of animal matter\nand thus is an important link in the food web.',
        332: 'Angora, Angora rabbit\nThey convert the energy in plant matter into energy of animal matter\nand thus is an important link in the food web.',
        333: 'Hamster, Cricetinae\nTheir habit of storing seeds may mean that they play a role in seed dispersal.',
        334: 'Porcupine, hedgehog hedgehogs\nThey have a role in controlling the populations of insect prey.',
        335: 'Fox squirrel, eastern fox squirrel, Sciurus niger\nSquirrels prey on seeds of trees hence play a significant role in shaping composition of forests.\nWhen squirrels bury seeds and forget them, these seeds are likely to sprout where they were placed.\n Squirrels, therefore, act to promote the growth of certain kinds of trees.',
        336: 'Marmot\nmarmots may act as seed dispersers and pollinators for the variety of grasses and flowers that they consume',
        337: 'Beaver, Castoridae\nThey are commonly referred to as ecosystem engineers\nThey make a dam which slows the flow of water in the stream and subsequently a pond or area of wetland is formed.\nThey cut down trees, they also bring more light to the forest floor.',
        338: 'Guinea pig, Cavia cobaya\nThey consume small amounts of plants, fruits, and seeds.',
        339: 'Sorrel(horse) Equus\nAs grazing animals, horses influence diversity and structure of the ecosystems\nThey have been important in seed dispersal of certain trees.\nThere are over 150 species of parasites documented in horses.',
        340: 'Zebra\nThey serve as a prey for certain mammalian carnivores\nZebras also serve as hosts for a variety of tick, bot-fly, nematode, and cestode species.\nAs grazers, mountain zebras may also aid in seed dispersal.',
        341: 'Hog, pig, grunter, squealer, Sus scrofa\nThrough their feeding, rooting and sometimes predatory behaviour,they have significant impacts on the ecological functioning.',
        342: 'Wild boar, boar, Sus scrofa\nWild boars often have a negative effect on the ecosystems, especially if they are an introduced species.\nThey can be very destructive to the habitats of other animals in the area.',
        343: 'Warthog, Phacochoerus africanus\nThey have a mutualistic relationship with birds, such as red-billed and yellow-billed oxpeckers.',
        344: 'Hippopotamus, hippo, river horse, Hippopotamus amphibius\nDaily activities both in and out of water create habitats for smaller organisms.\nFormation of hippo paths from water to land clears avenues that water can flow through.\nFlooding of these paths creates most of the lagoons that small fish retreat to during droughts.',
        345: 'Ox\nThey affect ecological processes at landscape like pollination.',
        346: 'Water buffalo, water ox, Asiatic buffalo, Bubalus bubalis\nThey affect ecological processes at landscape like pollination.',
        347: 'Bison\nTheir grazing and dust-bathing strongly influences the\ncomposition of plant communities and the communities of other animals.',
        348: 'Tup, male sheep\nThey are important predators of grasses and shrubs in their native landscapes\nThey are also important sources of prey for large predators.',
        349: 'Bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis\nThey are important predators of grasses and shrubs in their native landscapes\nThey are also important sources of prey for large predators.',
        350: 'Ibex, Capra ibex\nIbex probably influences the vegetational community as a browser',
        351: 'Hartebeest, Alcelaphus buselaphus\nThe hartebeest competes with cattle for grazing land.',
        352: 'Impala, Aepyceros melampus\nClassified as intermediate feeders, impalas are adapted to browsing and grazing.\nDue to hunting they are endangered.',
        353: 'Gazelle\nBecause of their foraging behavior, mountain gazelles\nprobably affect the plant communities where they are common.',
        354: 'Arabian camel, dromedary, Camelus dromedarius\nApart from being extremely useful to humans they are a host to a large number of parasites.',
        355: 'Llama, Lama glama\nThey browse on low vegetation and their padded foot does less\ndamage to the grazing area than the hooves of other livestock.',
        356: 'Weasel\nIt likely plays some role in regulating small rodent populations.',
        357: 'Mink\nMink are important predators of small mammals throughout their range.',
        358: 'Polecat, fitch, foulmart, foumart, Mustela putorius\nPolecats are important predators of small mammals in the ecosystems in which they live.',
        359: 'Black-footed ferret, ferret, Mustela nigripes\nBlack-footed ferrets help control populations of prairie dogs',
        360: 'Otter\nOtters important to their ecosystem as both a predator and prey',
        361: 'Skunk, polecat, wood pussy\nThe skunks overturn earth while digging for food and mix up the soil.\nThey help control pest population.',
        362: 'Badger\nIt is a home for several parasites.\nAlso, they aerate the soil by digging.\nThey create a habitat for other small animals through abandoned hog badger burrows.',
        363: 'Armadillo\nThey keep the termite and ant populations in check, in a small region.',
        364: 'Three-toed sloth, Bradypus tridactylus\nThey may impact the growth of trees through their folivory.',
        365: 'Orangutan, orangutang, Pongo pygmaeus\nSince fruits make up more than 60% their diets, they play a vital role in seed dispersal.',
        366: 'Gorilla, Gorilla gorilla\nThese animals may be important in structuring plant communities and help seed dispersal.',
        367: 'Chimpanzee, chimp, Pan troglodytes\nThese animals may be important in structuring plant communities and help seed dispersal.',
        368: 'Gibbon, Hylobates lar\nThey are most likely important for seed dispersal.',
        369: 'Siamang, Hylobates syndactylus, Symphalangus syndactylus\nAs frugivores, these primates are likely to be important seed dispersers.',
        370: 'Guenon, guenon monkey\nAs frugivores, these primates are likely to be important seed dispersers.',
        371: 'Patas, hussar monkey, Erythrocebus patas\nThey are most likely important for seed dispersal.',
        372: 'Baboon\nThese animals may be important in structuring plant communities and help seed dispersal.',
        373: 'Macaque\nThese animals may be important in structuring plant communities and help seed dispersal.',
        374: 'Langur\nThese animals may be important in structuring plant communities and help seed dispersal.',
        375: 'Colobus, colobus monkey\nThese animals may be important in structuring plant communities and help seed dispersal.',
        376: 'Proboscis monkey, Nasalis larvatus\nThese animals may be important in structuring plant communities and help seed dispersal.',
        377: 'Marmoset\nTheir help in controlling the insect population.',
        378: 'Capuchin, ringtail, Cebus capucinus\nThese animals may be important in structuring plant communities and help seed dispersal.',
        379: 'Howler monkey, howler\nThese animals may be important in structuring plant communities and help seed dispersal.',
        380: 'Titi, titi monkey\nThese animals may be important in structuring plant communities and help seed dispersal.',
        381: 'Spider monkey, Ateles geoffroyi\nThese animals may be important in structuring plant communities and help seed dispersal.',
        382: 'Squirrel monkey, Saimiri sciureus\nThese animals may be important in structuring plant communities and help seed dispersal.',
        383: 'Madagascar cat, ring-tailed lemur, Lemur catta\nRing-tailed lemurs contribute to the ecosystem by spreading seeds through their feces.',
        384: 'Indri, Indri indri, Indri brevicaudatus\nAs frugivores, indris probably help to disperse seeds.',
        385: 'Indian elephant, Elephas maximus\nThey eat a very large amount of food daily, which facilitates nutrient cycling.\nBecause of their large size, they transform the habitat by tearing down trees.\nThis creates gaps in the forest, allowing small animals to move around.\nThey also aid in seed dispersal.',
        386: 'African elephant, Loxodonta africana\nThey eat a very large amount of food daily, which facilitates nutrient cycling.\nBecause of their large size, they transform the habitat by tearing down trees.\nThis creates gaps in the forest, allowing small animals to move around.\nThey also aid in seed dispersal.',
        387: 'Lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens\nTney are an umbrella species: protecting them protects many threatened including clouded leopards,\nHimalayan black bears, and hundreds of bird species.',
        388: 'Giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca\nGiant panda population is closely tied to bamboo abundance and vice versa.\nPandas help to distribute the bamboo seeds over areas.',
        109: 'Brain coral, Diploria labyrinthiformis.\nBrain coral serves as homes for other organisms like algae in loose substrates of the ocean floor.',
        936: 'Cabbage Plant, Brassica oleracea var. capitata\nThey provide good food for insects while the plant is alive, and after the plant has begun to wither.',
        937: 'Broccoli Plant, Brassica oleracea var. italica\nThey provide good food for insects while the plant is alive, and after the plant has begun to wither.',
        938: 'Cauliflower Brassica oleracea var. botrytis\nThey provide good food for insects while the plant is alive, and after the plant has begun to wither.',
        939: 'Zucchini, courgette, Cucurbita pepo\nThis crop’s requirement for insect-mediated pollination is very significant\nWidely cultivated for livestock feed.',
        940: 'Spaghetti Squash, Cucurbita pepo\nThis vegetables requirement for insect-mediated pollination is very significant\nWidely cultivated for livestock feed.',
        941: 'Acorn Squash, Quercus\nSignificant for many animals dependent on acorns and the predators of those animals in forest ecosystem.',
        942: 'Butternut squash, Cucurbita moschata\nWidely cultivated for livestock feed.\nThis edible plants requirement for insect-mediated pollination is very significant',
        943: 'Cucumber, Cucumis sativus\nThis edible plants requirement for insect-mediated pollination is very significant',
        944: 'Artichoke, Cynara cardunculus\n An edible flower important for insect-mediated pollination',
        945: 'Bell pepper, Capsicum annuum\nAn edible plant important for insect-mediated pollination',
        946: 'Cardoon,  Cynara cardunculus\nA perennial vegetale with great adaptation in various soil and climate conditions',
        947: 'Mushroom\nThey break down organic matter in the forest to recycle essential nutrients.',
        948: 'Green apple plant, Granny Smith\nAn acre of apples will extract about 15 tons of carbon dioxide from the air each year\nThey also aid indirect pollination',
        949: 'Strawberry plant, Fragaria × ananassa\nAids indirect pollination and carbon dioxide removal from atmosphere',
        950: 'Orange plant, Citrus x sinensis\nAids indirect pollination and carbon dioxide removal from atmosphere',
        951: 'Lemon, Citrus × limon\nIts perennial framework can deposit the atmospheric carbon to the tune of 10-15 Mg C/ha/year,\n almost like any forest tree',
        952: 'Fig flower\nAids indirect pollination and carbon dioxide removal from atmosphere',
        953: 'Pineapple plant, ananas\nAids indirect pollination and carbon dioxide removal from atmosphere',
        954: 'Banana plantation, Musa\nA fruit that also regulates atmosphere, holds soil, and cycles nutrients.',
        955: 'Jackfruit, Artocarpus heterophyllus\nA fruit that also regulates atmosphere, holds soil, and cycles nutrients.',
        956: 'Custard apple\nA sweet fruit that helps insect-mediated pollination',
        957: 'Pomegranate, Punica granatum\nA fruit that also regulates atmosphere, holds soil, and cycles nutrients.',
        984: 'Rapeseed, Brassica napus\nIt is grown for the production of animal feed, edible vegetable oils, and biodiesel.',
        985: 'Daisy, Bellis perennis\nVery helpful in pollination as bees love daisy.',
        986: "Yellow lady's slipper, Cypripedium calceolus, Cypripedium parviflorum\nThis orchid has many documented pollinators",
        987: 'Corn, Maize, Zea mays\nThe world’s most dominant and productive crop, with global production yields of over 1 billion metric tons\nIt aids in removal of carbon dioxide from the atmosphere.',
        988: 'Acorn, Quercus\nSignificant for many animals dependent on acorns and the predators of those animals in forest ecosystem.\nWidely cultivated for livestock feed, ethanol, as well as for high fructose production',
        989: 'Rosehip, Rosa acicularis Lindl\nAids indirect pollination and carbon dioxide removal from atmosphere',
        990: 'Buckeye, horse chestnut, conker, Aesculus glabra\nA very rare seed used as a sedative, for relieving asthma and for the treatment of hemorrhoids',
        991: 'Coral fungus, Clavariaceae\nThey break down organic matter in the water systems to recycle essential nutrients in soil.',
        992: 'Agaric, Amanita muscaria\nThey break down dead and decaying organic matter and recycle them to essential nutrients in soil.',
        993: 'Gyromitra, Gyromitra esculenta\nThey break down dead and decaying organic matter and recycle them to essential nutrients in soil.',
        994: 'Stinkhorn, carrion fungus, Phallaceae\nThey break down dead and decaying organic matter and recycle them to essential nutrients in soil.',
        995: 'Earthstar, Geastrales\nThey break down dead and decaying organic matter and recycle them to essential nutrients in soil.',
        996: 'Hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa\nThey break down dead and decaying organic matter and recycle them to essential nutrients in soil.',
        997: 'Bolete, Boletus edulis\nThey break down dead and decaying organic matter and recycle them to essential nutrients in soil.',
    }
    return switcher.get(index, "Sorry!! No results found")


def ans():
    try:
        root.filename = filedialog.askopenfilename(
            initialdir="/C", title="select a file", filetypes=(("all files", "*.*"),))
        path = root.filename
        img = load_img(path, target_size=(224, 224, 3))
        img = img_to_array(img)
        img = img.reshape((1, img.shape[0], img.shape[1], img.shape[2]))
        img = preprocess_input(img)
        predictions = model.predict(img)
        top_indice = np.argsort(predictions)[0, ::-1][0]
        label = decode_predictions(predictions)
        label = label[0][0]
        answer = int(label[2] * 100)
        load = Image.open(path)
        load = load.resize((250, 200))
        render = ImageTk.PhotoImage(load)
        result = Label(root, image=render)
        result.image = render
        result.place(relx=0.5, rely=0.43, anchor="c")
        if switch_index(top_indice) == "Sorry!! No results found":
            Answer['text'] = switch_index(top_indice)
        else:
            Answer['text'] = "Probability of the class= " + \
                str(answer) + "\n" + switch_index(top_indice)
    except:
        Answer['text'] = 'Please select an image file that has one of the extensions: PNG, JPG, JPEG, BMP, PPM, TIF, and TIFF.'


canvas = tk.Canvas(root, height=535, width=800, bg='#B0CF99')
canvas.pack()
button = tk.Button(root, text="Select Image", font=("Helvetica", "12", "bold"),
                   bg="#fafd66", command=lambda: ans())
button.place(relx=0.5, rely=0.15, relheight=0.10, relwidth=0.20, anchor="c")
Answer = tk.Label(root, font=("Times", "11", "bold"))
Answer.place(relx=0.5, rely=0.75, anchor='c')
label = tk.Label(
    root, text="Welcome to our Wildlife Image Classifier!!", font=("Helvetica", "12", "bold"))
label.place(relx=0.5, rely=0.05, anchor="c")
root.title("Wildlife Classifier")
root.mainloop()
